[package]
name = "ytgrep"
version = "0.3.3"
authors = ["Tiago Carvalho <sugoiuguu@tfwno.gf>"]
edition = "2018"

[dependencies]
percent-encoding = "2.1.0"
reqwest = "0.9.24"
ajson = "0.2.4"
nix = "0.18.0"
