[package]
name = "ytgrep"
version = "0.4.0"
authors = ["Tiago Carvalho <sugoiuguu@tfwno.gf>"]
edition = "2018"

[dependencies]
percent-encoding = "2.1.0"
reqwest = { version = "0.11.8", features = ["blocking", "gzip"] }
ajson = "0.2.4"
